### ISSUE TITLE
Can't jump while on top of enemy

### ISSUE THREAD

**Issue by arcutright** [ianlav/EECS393IsaacGameThing#9] opened 2016-11-14 21:16 UTC
![capture](https://cloud.githubusercontent.com/assets/22824937/20283071/8823e808-aa85-11e6-9cbd-89d58f3579ee.PNG)
In this situation, jumping is disabled for some reason.
How am I supposed to bounce off of enemies like this?

**Comment by ianlav** [comment] 2016-11-15 02:02
cool as it would be, the jump logic gets reset when the player touches a platform, and I dont think the extra work to fix the logic to jump off enemies would be worth it

**Comment by arcutright** [comment] 2016-11-15 02:05
Extra work? Shouldn't that just be a tag comparison anyway?
ie, adding line 58 somewhere inside of 81 at [this file](https://github.com/ianlav/EECS393IsaacGameThing/blob/master/EECS393IsaacGameThing/Assets/Scripts/Characters/Player/PlayerMovement.cs)

**Comment by ianlav** [comment] 2016-11-15 02:08
Yes but then they could jump off the sides of enemies as well, like the flying enemies we're looking at adding

**Comment by arcutright** [comment] 2016-11-15 02:12
Can't you check the colliders for top/bottom? Pretty low priority issue either way

**Comment by ianlav** [comment] 2016-11-15 02:22
Hmmmm... not directly, but I can find the collision point, and if its, within 95% of the height of the enemy (cant say above center, since that could still be the sides, and 95% just to account for unity inaccuracy), reset the jump counter. The issue is if the collider gets resized the code has to be reworked. Might be able to generalize it, I'll look into it. Other option would be a second trigger on top of each enemy, but thats not ideal

**Comment by ianlav** [comment] 2016-11-15 02:35
Fixed in latest commit

**Closed by ianlav** 2016-11-15 02:35 UTC

**Comment by arcutright** [comment] 2016-11-15 02:37
c377b9cf640f2cb4a2869322a49f7250cfbf20e4
